# Generated by Django 6.0.8 on 2026-08-16 16:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('clinical', '0002_medicalcondition'),
        ('doctors', '0002_doctoravailability'),
        ('patients', '0004_alter_patient_height_cm_alter_patient_weight_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalEncounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('chief_complaint', models.TextField(blank=True)),
                ('symptoms', models.TextField(blank=True)),
                ('examination_findings', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_encounter', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_encounters', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_encounters', to='patients.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
