# Generated by Django 6.0.8 on 2026-08-16 17:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0005_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('action_type', models.CharField(choices=[('FOLLOW_UP', 'Follow Up'), ('LAB_TEST', 'Lab Test'), ('REFERRAL', 'Referral'), ('PROCEDURE', 'Procedure'), ('OTHER', 'Other')], default='FOLLOW_UP', max_length=20)),
                ('description', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_actions', to='clinical.clinicalencounter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
