# Generated by Django 6.0.8 on 2026-08-18 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0006_followupaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ENCOUNTER_CREATED', 'Encounter Created'), ('DIAGNOSIS_CREATED', 'Diagnosis Created'), ('PRESCRIPTION_CREATED', 'Prescription Created'), ('FOLLOW_UP_CREATED', 'Follow Up Created'), ('ENCOUNTER_COMPLETED', 'Encounter Completed')], max_length=50)),
                ('target_type', models.CharField(max_length=100)),
                ('target_id', models.CharField(max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_audit_events', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='clinical.clinicalencounter')),
            ],
            options={
                'db_table': 'clinical_audit_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
