# Generated by Django 6.0.8 on 2026-08-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_healthos_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='healthos_uid',
            field=models.CharField(db_index=True, editable=False, max_length=20, unique=True),
        ),
    ]
