# Generated by Django 6.0.8 on 2026-08-12 15:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0004_alter_patient_height_cm_alter_patient_weight_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?[0-9]{10,15}$')])),
                ('relationship', models.CharField(choices=[('PARENT', 'Parent'), ('SPOUSE', 'Spouse'), ('SIBLING', 'Sibling'), ('CHILD', 'Child'), ('FRIEND', 'Friend'), ('RELATIVE', 'Relative'), ('OTHER', 'Other')], max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='patients.patient')),
            ],
            options={
                'db_table': 'emergency_contacts',
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
    ]
