# Generated by Django 6.0.8 on 2026-08-13 05:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0004_alter_patient_height_cm_alter_patient_weight_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('record_type', models.CharField(choices=[('DIAGNOSIS', 'Diagnosis'), ('PRESCRIPTION', 'Prescription'), ('LAB_REPORT', 'Lab Report'), ('IMAGING', 'Imaging'), ('PROCEDURE', 'Procedure'), ('DISCHARGE_SUMMARY', 'Discharge Summary'), ('OTHER', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('record_date', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patient')),
            ],
            options={
                'db_table': 'medical_records',
                'ordering': ['-record_date', '-created_at'],
            },
        ),
    ]
